name: clockify_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hive: ^2.2.3
  pie_chart: ^5.4.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  uuid: ^4.4.2
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
